// Copyright 2026 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  Child policies of the mutation pool: they hear what the pool sees and
//  shape it through owner-mediated actions.
//

/// Where one executed input came from.
public enum PoolIterationSource: Sendable, Equatable {
    /// The residual queue: seeds, `queueInputs`, or a bus plugin's
    /// `selectForMutation` burst.
    case queue
    /// Freshly generated by the mutators.
    case generated
    /// A scheduler-directed mutant of pool entry `parent`.
    case pool(parent: Int)
}

/// What one fuzz iteration looked like from the pool's perspective.
public struct PoolIterationOutcome: Sendable {
    public let source: PoolIterationSource
    /// Non-nil exactly when the coverage strategy accepted the input.
    public let newCoverage: SparseCoverage?

    public init(source: PoolIterationSource, newCoverage: SparseCoverage?) {
        self.source = source
        self.newCoverage = newCoverage
    }
}

/// Events the pool owner sends to its child policies.
///
/// `inserted`/`removed` fire for EVERY membership change, including ones
/// caused by other children — the owner re-broadcasts so policies never need
/// to talk to each other to stay consistent.
public enum PoolEvent {
    /// An input executed. Use `outcome.source` for lineage attribution.
    case iteration(PoolIterationOutcome)
    /// An entry was admitted to the pool.
    case inserted(id: Int, coverage: SparseCoverage)
    /// An entry left the pool (its ID is never reused).
    case removed(id: Int)
    /// The owner is about to draw a new focus entry. The moment for lazy
    /// policies to flush batched weight updates — fires once per draw, not
    /// once per iteration.
    case willDraw
}

/// Actions a child policy returns to the pool owner.
///
/// Membership and weights are the only levers; what executes next is the
/// owner's decision alone.
public enum PoolAction {
    /// Evict an entry from the draw set. Its ID stays valid (never reused);
    /// evicting the current focus ends that burst.
    case remove(id: Int)
    /// Set an entry's draw weight. Negative values clamp to zero; an
    /// all-zero pool falls back to uniform draws.
    case setWeight(id: Int, Double)
}

/// A composable policy attached to the mutation pool.
///
/// One instance serves one engine (built fresh per engine by the
/// `MutationScheduler` factory), so implementations hold plain mutable state
/// without synchronization. Events arrive on the engine's task.
public protocol PoolPlugin: AnyObject {
    func handle(event: PoolEvent) -> [PoolAction]
}

/// The pool's admission rule: which accepted inputs become pool entries.
///
/// Admission is a dedicated role (not a regular `PoolPlugin`) so exactly one
/// component decides membership — children advise weights and evictions but
/// can never double-insert. An admission verdict can carry evictions of its
/// own (REDUCE: a winner bankrupting previous owners).
public struct PoolAdmission: Sendable {
    struct Verdict {
        let admit: Bool
        /// Existing entries this admission displaces from the pool.
        let evict: [Int]
    }

    /// Builds a fresh per-engine judge over the accepted input's coverage.
    let makeJudge: @Sendable () -> (SparseCoverage) -> Verdict

    init(makeJudge: @escaping @Sendable () -> (SparseCoverage) -> Verdict) {
        self.makeJudge = makeJudge
    }

    /// Every strategy-accepted input joins the pool, nothing ever leaves.
    /// The behavior of the classic corpus-mutation loop.
    public static let everyDiscovery = PoolAdmission(
        makeJudge: { { _ in Verdict(admit: true, evict: []) } })

    /// libFuzzer's corpus model: an input joins the pool only by *owning*
    /// coverage features — claiming unowned ones, or stealing from a larger
    /// owner (REDUCE; the covered-edge count is the size metric, ties don't
    /// steal). An entry that loses its last feature leaves the pool. Bounds
    /// the pool by the feature space regardless of how often the coverage
    /// strategy says "interesting"; rejected accepts get no burst and no
    /// residence (strict semantics).
    ///
    /// Features today are the covered edge indices; for an order-sensitive
    /// strategy like `.pathTrie` this is deliberately coarser than its
    /// acceptance criterion — that's the flood-control point.
    public static let featureOwnership = PoolAdmission(makeJudge: {
        var ledger = FeatureOwnershipLedger()
        return { coverage in
            let verdict = ledger.judge(features: coverage.indices, size: coverage.count)
            return Verdict(admit: verdict.admit, evict: verdict.evict)
        }
    })
}
