// Copyright 2026 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  The engine-facing scheduler contract. A scheduler decides what the engine
//  runs next and what it retains, reading whatever signals it needs out of the
//  per-execution `RawExecutionContext`. The engine is blind to those signals:
//  coverage-driven pools, branch-distance schedulers (FOX-style), and anything
//  not yet imagined all conform to this one protocol from a module that only
//  imports PropertyTestingKit.
//

/// What the engine should run next.
public enum SchedulerDirective: Equatable, Sendable {
    /// Generate a fresh input from the mutators.
    case generate
    /// Materialize one single-step mutant of retained entry `id`.
    case mutate(id: Int)
}

/// Where one executed input came from.
public enum SchedulerSource: Equatable, Sendable {
    /// The residual queue: seeds or `queueInputs`.
    case queue
    /// Freshly generated by the mutators.
    case generated
    /// A scheduler-directed mutant of retained entry `parent`.
    case pool(parent: Int)
}

/// Decides which inputs the engine runs and which it retains.
///
/// One instance serves one engine (built fresh per engine by a
/// `MutationScheduler` factory), so implementations hold plain mutable state
/// without synchronization. Events arrive on the engine's task.
///
/// The engine consults a scheduler through exactly two calls per iteration:
/// `observe` (report what just ran) and `next` (decide what runs next). The
/// scheduler reads whatever instrumentation it needs out of the context handed
/// to `observe`; the engine names no signal.
public protocol SchedulerCore: AnyObject {
    /// The instrumentation signals this scheduler reads. The engine installs
    /// only these probes, so a scheduler that wants nothing exotic pays for
    /// nothing exotic.
    static var requiredProbes: [any InstrumentationKey.Type] { get }

    /// Report one executed iteration. Read what you care about out of
    /// `context`, update your own state, and return the new entry's ID when the
    /// input should be retained (the engine then stores it at that index;
    /// IDs are sequential and never reused). Return `nil` to retain nothing.
    func observe(_ context: RawExecutionContext, source: SchedulerSource) -> Int?

    /// Decide what the engine runs next.
    func next() -> SchedulerDirective
}
