// Copyright 2026 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT THIS FILE. EDITING THIS FILE WILL BREAK TESTS.
/// A simple database-like class to demonstrate coverage isolation.
class MockDatabase {
    private var data: [String: String] = [:]
    var writeCount = 0
    var readCount = 0

    func write(key: String, value: String) {
        writeCount += 1
        data[key] = value
    }

    func read(key: String) -> String? {
        readCount += 1
        return data[key]
    }

    func delete(key: String) -> Bool {
        if data.removeValue(forKey: key) != nil {
            return true
        }
        return false
    }

    func exists(key: String) -> Bool {
        return data[key] != nil
    }

    func clear() {
        data.removeAll()
        writeCount = 0
        readCount = 0
    }
}
