// DO NOT EDIT THIS FILE. EDITING THIS FILE WILL BREAK TESTS.
/// A simple database-like class to demonstrate coverage isolation.
class MockDatabase {
    private var data: [String: String] = [:]
    var writeCount = 0
    var readCount = 0

    func write(key: String, value: String) {
        writeCount += 1
        data[key] = value
    }

    func read(key: String) -> String? {
        readCount += 1
        return data[key]
    }

    func delete(key: String) -> Bool {
        if data.removeValue(forKey: key) != nil {
            return true
        }
        return false
    }

    func exists(key: String) -> Bool {
        return data[key] != nil
    }

    func clear() {
        data.removeAll()
        writeCount = 0
        readCount = 0
    }
}
