// DO NOT EDIT THIS FILE. EDITING THIS FILE WILL BREAK TESTS.
/// A service that uses the database.
class UserService {
    let db: MockDatabase

    init(db: MockDatabase) {
        self.db = db
    }

    func createUser(id: String, name: String) -> Bool {
        if db.exists(key: "user:\(id)") {
            return false // User already exists
        }
        db.write(key: "user:\(id)", value: name)
        return true
    }

    func getUser(id: String) -> String? {
        return db.read(key: "user:\(id)")
    }

    func deleteUser(id: String) -> Bool {
        return db.delete(key: "user:\(id)")
    }

    func updateUser(id: String, name: String) -> Bool {
        if !db.exists(key: "user:\(id)") {
            return false // User doesn't exist
        }
        db.write(key: "user:\(id)", value: name)
        return true
    }
}
